title: mRM configuration
description: Configuration for the multi-scale routing model (mRM) in mHM.
x-fortran-namelist: config_mrm
type: object
properties:
  resolution:
    type: array
    items:
      type: number
      x-fortran-kind: dp
      exclusiveMinimum: 0.0
    x-fortran-shape: max_domains
    x-fortran-flex-tail-dims: 1
    title: mRM resolution (L3)
    description: Resolution of the mRM routing grid, level 3.
    examples: [[0.1]]
  river_net_order_root_based:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: max_domains
    title: Flag for root based river network ordering.
    description: |-
      Flag to indicate if the river network is ordered in root based order.
      If false, the ordering is leaf based.
      Root based ordering results in more equal distributed level sizes for parallelization.
      Leaf based ordering has huge levels of nodes at the headwaters, which can lead to load balancing issues.
    examples: [[true]]
  river_net_omp_level_min:
    type: array
    items:
      type: integer
      x-fortran-kind: i4
      default: 0
      minimum: 0
    x-fortran-shape: max_domains
    title: Minimum level size for OpenMP parallelization.
    description: |-
      Minimum level size in the river network where OpenMP parallelization starts.
      Levels smaller than this size are always computed serially.
      This can be used to avoid parallelization overhead for small levels of the river network,
      especially when ordering is leaf based.
      By default: threads * 8 (indicated by 0)
    examples: [[100]]
  scc_gauges_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: max_domains
    x-fortran-flex-tail-dims: 1
    title: Path for SCC gauges NetCDF file.
    examples: [["scc_gauges.nc"]]
  output_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: max_domains
    x-fortran-flex-tail-dims: 1
    title: Path for output file.
    examples: [["mrm_output.nc"]]
  output_node_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: max_domains
    x-fortran-flex-tail-dims: 1
    title: Path for node based output file.
    examples: [["mrm_node_output.nc"]]
  read_restart:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: max_domains
    title: Read restart
  read_restart_fluxes:
    type: array
    items:
      type: boolean
      default: true
    x-fortran-shape: max_domains
    title: Read restart fluxes
  restart_input_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: max_domains
    x-fortran-flex-tail-dims: 1
    title: Restart input path
    examples: [["mrm_restart_in.nc"]]
  write_restart:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: max_domains
    title: Write restart
  restart_output_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: max_domains
    x-fortran-flex-tail-dims: 1
    title: Restart output path
    examples: [["mrm_restart_out.nc"]]
  albedo_water:
    type: number
    x-fortran-kind: dp
    default: 0.15
    title: Albedo of open water
    description: |-
      Albedo of open water bodies.
      (0.15 for tilt angle between 10 and 20 degrees -> Wanders et.al. 2019)
  pt_a_water:
    type: number
    x-fortran-kind: dp
    default: 1.26
    title: Priestley-Taylor alpha
    description: |-
      Priestley-Taylor alpha parameter for PET on open water.
      (1.26 -> Gordon Bonan 2015)
  emissivity_water:
    type: number
    x-fortran-kind: dp
    default: 0.96
    title: Emissivity of water
    description: |-
      Emissivity of water.
      (0.96 -> Wanders et.al. 2019)
  turb_heat_ex_coeff:
    type: number
    x-fortran-kind: dp
    default: 20.0
    title: Turbulent heat exchange coefficient
    description: |-
      Turbulent heat exchange coefficient.
      (20.0 -> Wanders et.al. 2019)
  max_iter:
    type: integer
    x-fortran-kind: i4
    default: 50
    title: Max number of iterations
    description: |-
      Maximum number of iterations for the iterative solver for river temperature.
  delta_iter:
    type: number
    x-fortran-kind: dp
    default: 0.01
    title: Convergence criterion iteration
    description: |-
      Convergence criteria for iterative solver for resulting river temperature.
      Given as difference for iteratively estimated temperature in K
  step_iter:
    type: number
    x-fortran-kind: dp
    default: 5.0
    title: Maximal step in iteration
    description: |-
      Maximal step allowed in iteration for river temperature in K.
      Used to avoid divergence of the iterative solver.
required:
  - resolution
