name: Continuous Integration

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "develop"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_sdist:
    name: sdist
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build sdist
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build --sdist --outdir dist-sdist .

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist-sdist/*.tar.gz

  build_wheels:
    name: wheels for ${{ matrix.cfg.os }} / ${{ matrix.cfg.arch }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
        # - { os: ubuntu-24.04, arch: x86_64, shell: bash }
        # - { os: macos-13, arch: x86_64, shell: bash }
        # - { os: macos-14, arch: arm64, shell: bash }
        - { os: windows-2022, arch: AMD64, shell: "msys2 {0}" }
    defaults:
      run:
        shell: ${{ matrix.cfg.shell }}

    steps:
      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          install: >-
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-netcdf-fortran

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS: ${{ matrix.cfg.arch }}
        with:
          output-dir: dist-wheel-${{ matrix.cfg.os }}-${{ matrix.cfg.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: dist-wheel-${{ matrix.cfg.os }}-${{ matrix.cfg.arch }}
          path: ./dist-wheel-${{ matrix.cfg.os }}-${{ matrix.cfg.arch }}/*.whl

  upload_to_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist

      - name: Publish to Test PyPI
        # only if working on main
        if: github.ref == 'refs/heads/develop'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.test_pypi_api_token }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Publish to PyPI
        # only if tagged
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_api_token }}
